"""support external google reviews

Revision ID: 3c18912afb0a
Revises: 176565c7b04e
Create Date: 2026-09-05 12:41:00.221872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c18912afb0a'
down_revision: Union[str, Sequence[str], None] = '176565c7b04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('source', sa.String(length=20), server_default='app', nullable=False))
    op.add_column('reviews', sa.Column('external_review_id', sa.String(length=255), nullable=True))
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('uq_reviews_source_external_review_id', 'reviews', ['source', 'external_review_id'])
    op.create_check_constraint(op.f('ck_reviews_review_source_allowed'), 'reviews', "source IN ('app', 'google')")
    op.add_column('vendors', sa.Column('directory_id', sa.String(length=10), nullable=True))
    op.create_unique_constraint('uq_vendors_directory_id', 'vendors', ['directory_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vendors_directory_id', 'vendors', type_='unique')
    op.drop_column('vendors', 'directory_id')
    op.drop_constraint(op.f('ck_reviews_review_source_allowed'), 'reviews', type_='check')
    op.drop_constraint('uq_reviews_source_external_review_id', 'reviews', type_='unique')
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reviews', 'external_review_id')
    op.drop_column('reviews', 'source')
    # ### end Alembic commands ###
