"""add reddit comments table

Revision ID: 8761d4e9277e
Revises: 9f2e4c6a8b0d
Create Date: 2026-09-09 15:27:44.856221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8761d4e9277e'
down_revision: Union[str, Sequence[str], None] = '9f2e4c6a8b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_comments',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('reddit_comment_id', sa.String(length=32), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('thread_id', sa.String(length=32), nullable=False),
    sa.Column('thread_title', sa.Text(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mentioned_vendors', sa.JSON(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_reddit_comments_vendor_id_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reddit_comments')),
    sa.UniqueConstraint('reddit_comment_id', name=op.f('uq_reddit_comments_reddit_comment_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_comments')
    # ### end Alembic commands ###
