"""add maps_url to google reviews

Revision ID: a2ed0740297f
Revises: b1c3d5e7f9a2
Create Date: 2026-09-26 14:16:37.703672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ed0740297f'
down_revision: Union[str, Sequence[str], None] = 'b1c3d5e7f9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_reviews', sa.Column('maps_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_reviews', 'maps_url')
    # ### end Alembic commands ###
