"""add review votes

Revision ID: efceea3e9e44
Revises: 3c0cb84a736b
Create Date: 2026-10-05 16:32:21.911855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efceea3e9e44'
down_revision: Union[str, Sequence[str], None] = '3c0cb84a736b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_votes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(length=4), nullable=False),
    sa.CheckConstraint("vote_type IN ('up', 'down')", name=op.f('ck_review_votes_vote_type_allowed')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_votes_review_id_reviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_review_votes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_votes')),
    sa.UniqueConstraint('review_id', 'user_id', name='uq_review_votes_review_user')
    )
    op.create_index('ix_review_votes_review_id', 'review_votes', ['review_id'], unique=False)
    op.create_index('ix_review_votes_user_id', 'review_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_votes_user_id', table_name='review_votes')
    op.drop_index('ix_review_votes_review_id', table_name='review_votes')
    op.drop_table('review_votes')
    # ### end Alembic commands ###
